### ISSUE TITLE
localhost:3333/misc/contacts?key=123 não funcionando

### ISSUE THREAD

**Issue by aliceTheFarmer** [renatoiub/whatsapp-hard-api-node#6]
Parabéns pela implementação! 

duas coisinhas: 
localhost:3333/misc/contacts?key=123 não retorna nenhum contato, mesmo depois de um bom tempo já na conta. 

a outra é uma sugestão mesmo:

colocar um endpoint para pegar o displayName da pessoa... 

Obrigada!

**Comment by renatoiub** [comment]
Olá @aliceTheFarmer 
Sobre contatos: Ou retorna que os contatos ainda não foram carregados ou retorna os contatos. Se não retornou nada pode ter algo errado. Hoje existe um bug na lib de integração com o Whatsapp (baileys) que as vezes não retorna os contatos, principalmente se você estiver conectada a vários dispositivos e também quando fica aquela mensagem: Mantenha o app aberto para a sincronização.. A recomendação é que você recrie a instancia.

Sobre as sugestões: Você consegue algumas informações dos clientes usando o método de verificação de um número no WhatsApp (Is On Whatsapp?) e também em get User status.
