### ISSUE TITLE
Receiving "fatal: Could not read from remote repository"

### ISSUE THREAD

**Issue by jhernancanom** [renatoiub/whatsapp-hard-api-node#7]
Hello, friends.

When **`npm i`** I am receiving 

`**fatal: Could not read from remote repository**`.

What do I need to do? ((see image))

Is there any way for me to change the command 

`**git --no-replace-objects ls-remote ssh://git@github.com/renatoiub/baileys.git**`

for it run fine? (I can download Baileys ``https://github.com/renatoiub/Baileys`` the same way I downloaded WhatsApp-Hard-API-Node:
https://github.com/renatoiub/whatsapp-hard-api-node

How should I proceed?

![image](https://github.com/user-attachments/assets/3c1c70b8-acda-42ed-8aba-06b240aa2042)

**Comment by renatoiub** [comment]
Hi, It may have been a momentary glitch on github. Clone the repository again and try reinstalling. I tested it here and everything worked fine.

**Comment by jhernancanom** [comment]
Ago-24-2024, 11:25pm Colombia.

The error is the same: not resolved if re-trying.

**Some one can help me to install this repository by hand?**

![image](https://github.com/user-attachments/assets/a46bee8a-3c79-44a0-826d-e017460c757e)
